# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "statefiles"
    key                  = "workspace1/terraform.tfstate"
    resource_group_name  = "dmytro-terragrunt-statefiles"
    storage_account_name = "dmytro8gsd97yg"
    subscription_id      = "b4f7ead0-14f6-453a-b41b-e4c8df68890d"
  }
}
